<?php

namespace Tests\Feature;

use Database\Seeders\CategorySeeder;
use Database\Seeders\CounterSeeder;
use Illuminate\Database\Query\Builder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Tests\TestCase;

class QueryBuilderTest extends TestCase
{
    // setup
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::delete("delete from products");
        DB::delete("delete from categories");
        DB::delete("delete from counters");
    }

    // query builder insert
    public function testInsert()
    {
        // table categories
        // tambah data dengan query builder
        DB::table("categories")->insert([
            // kalau datanya sudah ada, maka tidak akan di tambahkan
            "id" => "GADGET",
            "name" => "Gadget"
        ]);
        DB::table("categories")->insert([
            "id" => "FOOD",
            "name" => "Food"
        ]);

        // select data
        $result = DB::select("select count(id) as total from categories");
        // hasilnya harus
        self::assertEquals(2, $result[0]->total);
    }

    // query builder insert
    public function testSelect()
    {
        // memanggil 2 insert data yang tadi Gaged dan Food
        $this->testInsert();

        // lalu table categories, select dari kolom "id dan name", lalu get() ambil semua datanya, query builder select 
        $collection = DB::table("categories")->select(["id", "name"])->get();
        // hasinya tidak boleh null/kosong
        self::assertNotNull($collection);

        // kita log setiap datanya
        $collection->each(function ($item) {
            Log::info(json_encode($item));
        });
    }

    public function insertCategories()
    {
        DB::table("categories")->insert([
            "id" => "SMARTPHONE",
            'name' => 'Smartphone',
            'created_at' => '2020-10-10 10:10:10'
        ]);
        DB::table("categories")->insert([
            "id" => "FOOD",
            'name' => 'Food',
            'created_at' => '2020-10-10 10:10:10'
        ]);
        DB::table("categories")->insert([
            "id" => "LAPTOP",
            'name' => 'Laptop',
            'created_at' => '2020-10-10 10:10:10'
        ]);
        DB::table("categories")->insert([
            "id" => "FASHION",
            'name' => 'Fashion',
            'created_at' => '2020-10-10 10:10:10'
        ]);
    }

    // public function insertCategories()
    // {
    //     $this->seed(CategorySeeder::class);
    // }

    // query builder wh
    public function testWhere()
    {
        // ambil dari function insertCategories
        $this->insertCategories();

        // table categories
        $collection = DB::table("categories")->where(function (Builder $builder) {
            // where(column, operator, value), AND column operator value
            $builder->where('id', '=', 'SMARTPHONE');

            // orWhere(column, operator, value) OR (condition)
            $builder->orWhere('id', '=', 'LAPTOP');
            // SELECT * FROM categories WHERE (id = smartphone OR id = laptop)
        })->get();

        // hasilnya
        self::assertCount(2, $collection);
        $collection->each(function ($item) {
            Log::info(json_encode($item));
        });
    }

    // where between method
    public function testWhereBetween()
    {
        // ambil dari function insertCategories
        $this->insertCategories();

        // table categories
        $collection = DB::table("categories")
            // "created_at" = colum, ["array"]
            ->whereBetween("created_at", ["2020-09-10 10:10:10", "2020-11-10 10:10:10"]) // WHERE column BETWEEN value1 AND value2
            ->get(); // ambil semua data

        // hasilnya akan data ke 4
        self::assertCount(4, $collection);
        $collection->each(function ($item) {
            // kita log setiap datanya
            Log::info(json_encode($item));
        });
    }

    // where in method
    public function testWhereIn()
    {
        // ambil dari function insertCategories
        $this->insertCategories();

        // table categories
        $collection = DB::table("categories")
            // "id" = colum, ["array"]
            ->whereIn("id", ["SMARTPHONE", "LAPTOP"]) // WHERE column IN (array)
            ->get(); // ambil semua datanya

        // hasilnya akan data ke 2
        self::assertCount(2, $collection);
        $collection->each(function ($item) {
            // kita log setiap datanya
            Log::info(json_encode($item));
        });
    }

    // where null method
    public function testWhereNull()
    {
        // ambil dari function insertCategories
        $this->insertCategories();

        // table categories
        $collection = DB::table("categories")
            ->whereNull("description") // WHERE column IS NULL
            ->get(); // ambil semua data

        // hasilnya akan dapat 4 datanya
        self::assertCount(4, $collection);
        $collection->each(function ($item) {
            // kita log setiap datanya
            Log::info(json_encode($item));
        });
    }

    // where data method
    public function testWhereDate()
    {
        // ambil dari function insertCategories
        $this->insertCategories();

        // table categories
        $collection = DB::table("categories")
            // "created_at" = column, "2020" = value
            ->whereDate("created_at", "2020-10-10") // WHERE DATE(column) = value
            ->get(); // ambil semua data

        // hasilnya akan 4 data
        self::assertCount(4, $collection);
        $collection->each(function ($item) {
            // kita log setiap datanya
            Log::info(json_encode($item));
        });
    }

    // query builder update
    public function testUpdate()
    {
        // ambil dari function insertCategories
        $this->insertCategories();

        // table categories
        DB::table("categories")
            ->where("id", "=", "SMARTPHONE") // dari id nya semartphone
            ->update(["name" => "Handphone"]); // melakukan update untuk kolom name

        // table categories
        $collection = DB::table("categories")
            ->where("name", "=", "Handphone")
            ->get(); // ambil semua data

        // hasilnya 1 data
        self::assertCount(1, $collection);
        $collection->each(function ($item) {
            // kita log setiap datanya
            Log::info(json_encode($item));
        });
    }

    // upsert (Update or Insert)
    public function testUpsert()
    {
        // table categories
        DB::table("categories")
            ->updateOrInsert([
                "id" => "VOUCHER" // updateOrInsert, melakukan update, jika datanya tidak ada, maka akan dilakukan insert data baru
            ], [
                "name" => "Voucher",
                "description" => "Ticket and Voucher",
                "created_at" => "2020-10-10 10:10:10"
            ]);

        // table categories
        $collection = DB::table("categories")
            ->where("id", "=", "Voucher") // id sama dengan voucher
            ->get(); // ambil semua data

        // hasilnya ada 1 data
        self::assertCount(1, $collection);
        $collection->each(function ($item) {
            // kita log setiap datanya
            Log::info(json_encode($item));
        });
    }

    // increment dam decremenet
    // public function testIncrement()
    // {
    //     // $this->seed(CounterSeeder::class);

    //     // table counters
    //     DB::table("counters")
    //         ->where('id', '=', 'sample') // and column operator value
    //         // 'counter'=column, 1=increment 
    //         ->increment('counter', 1);  // untuk malakukan increment

    //     // table counters
    //     $collection = DB::table("counters")
    //         // 'id'= column, "=" = operator, 'sample' = value
    //         ->where('id', '=', 'sample') // and column operator value
    //         ->get(); // ambil semua datanya

    //     // hasilnya ada 1 data
    //     self::assertCount(1, $collection);
    //     $collection->each(function ($item) {
    //         // kita log setiap datanya
    //         Log::info(json_encode($item));
    //     });
    // }

    // query builder delete
    public function testDelete()
    {
        // ambil dari function insertCategories
        $this->insertCategories();

        // aksinya
        DB::table("categories")
            ->where('id', '=', 'SMARTPHONE') // and column operator value
            ->delete(); // untuk melakukan sql delete

        // hasilnya
        $collection = DB::table("categories")
            ->where("id", "=", "SMARTPHONE") // and column operator value
            ->get(); // ambil semua data

        // hasilnya data 0/tidak ada
        self::assertCount(0, $collection);
    }

    // insert table product
    public function insertProducts()
    {
        // ambil dari function insertCategories
        $this->insertCategories();

        // ambil table products
        DB::table("products")
            // tambah datanya
            ->insert([
                "id" => "1",
                "name" => "iPhone 14 Pro Max",
                "category_id" => "SMARTPHONE",
                "price" => 20000000
            ]);
        DB::table("products")
            ->insert([
                "id" => "2",
                "name" => "Samsung Galaxy S21 Ultra",
                "category_id" => "SMARTPHONE",
                "price" => 18000000
            ]);
    }

    // query builder Join
    public function testJoin()
    {
        // ambil dari function insertProducts
        $this->insertProducts();

        $collection = DB::table("products")
            // join(table, column, operator, ref_column), untuk JOIN atau INNER JOIN
            ->join("categories", "products.category_id", '=', 'categories.id')
            ->select("products.id", "products.name", "products.price", "categories.name as category_name") // akan jadi id
            ->get(); // ambil semua datanya

        // hasil nya akan ada 2 data baru
        self::assertCount(2, $collection);
        $collection->each(function ($item) {
            // kita log setiap datanya
            Log::info(json_encode($item));
        });
    }

    // query builder ordering
    public function testOrdering()
    {
        // ambil dari function insertProducts
        $this->insertProducts();

        $collection = DB::table("products")
            ->whereNotNull("id") // id tidak boleh null/kosong
            // orderBy(column, order) dimana order bisa asc atau desc
            ->orderBy("price", "desc")
            ->orderBy("name", "asc")
            ->get(); // ambil semua data

        // hasil nya ada 2 data
        self::assertCount(2, $collection);
        $collection->each(function ($item) {
            // kita log setiap datanya
            Log::info(json_encode($item));
        });
    }

    // query builder paging
    public function testPaging()
    {
        // ambil dari function insertProducts
        $this->insertCategories();

        // ambil database categories
        $collection = DB::table("categories")
            ->skip(0) // melakukan offset
            ->take(2) // melakukan limit
            ->get(); // ambil semua data

        // hasilnya ada 2 data
        self::assertCount(2, $collection);
        $collection->each(function ($item) {
            // kita log setiap datanya
            Log::info(json_encode($item));
        });
    }

    // public function insertManyCategories()
    // {
    //     for ($i = 0; $i < 100; $i++) {
    //         DB::table("categories")->insert([
    //             "id" => "CATEGORY-$i",
    //             "name" => "Category $i",
    //             "created_at" => "2020-10-10 10:10:10"
    //         ]);
    //     }
    // }

    // public function testChunk()
    // {
    //     $this->insertManyCategories();

    //     DB::table("categories")->orderBy("id")
    //         ->chunk(10, function ($categories) {
    //             self::assertNotNull($categories);
    //             Log::info("Start Chunk");
    //             $categories->each(function ($category) {
    //                 Log::info(json_encode($category));
    //             });
    //             Log::info("End Chunk");
    //         });
    // }

    // public function testLazy()
    // {
    //     $this->insertManyCategories();

    //     $collection = DB::table("categories")->orderBy("id")->lazy(10)->take(3);
    //     self::assertNotNull($collection);

    //     $collection->each(function ($item) {
    //         Log::info(json_encode($item));
    //     });
    // }

    // public function testCursor()
    // {
    //     $this->insertManyCategories();

    //     $collection = DB::table("categories")->orderBy("id")->cursor();
    //     self::assertNotNull($collection);

    //     $collection->each(function ($item) {
    //         Log::info(json_encode($item));
    //     });
    // }

    // public function testAggregate()
    // {
    //     $this->insertProducts();

    //     $result = DB::table("products")->count("id");
    //     self::assertEquals(2, $result);

    //     $result = DB::table("products")->min("price");
    //     self::assertEquals(18000000, $result);

    //     $result = DB::table("products")->max("price");
    //     self::assertEquals(20000000, $result);

    //     $result = DB::table("products")->avg("price");
    //     self::assertEquals(19000000, $result);

    //     $result = DB::table("products")->sum("price");
    //     self::assertEquals(38000000, $result);
    // }

    // public function testQueryBuilderRaw()
    // {
    //     $this->insertProducts();

    //     $collection = DB::table("products")
    //         ->select(
    //             DB::raw("count(id) as total_product"),
    //             DB::raw("min(price) as min_price"),
    //             DB::raw("max(price) as max_price"),
    //         )->get();

    //     self::assertEquals(2, $collection[0]->total_product);
    //     self::assertEquals(18000000, $collection[0]->min_price);
    //     self::assertEquals(20000000, $collection[0]->max_price);
    // }

    // public function insertProductFood()
    // {
    //     DB::table("products")->insert([
    //         "id" => "3",
    //         "name" => "Bakso",
    //         "category_id" => "FOOD",
    //         "price" => 20000
    //     ]);
    //     DB::table("products")->insert([
    //         "id" => "4",
    //         "name" => "Mie Ayam",
    //         "category_id" => "FOOD",
    //         "price" => 20000
    //     ]);
    // }

    // public function testGroupBy()
    // {
    //     $this->insertProducts();
    //     $this->insertProductFood();

    //     $collection = DB::table("products")
    //         ->select("category_id", DB::raw("count(*) as total_product"))
    //         ->groupBy("category_id")
    //         ->orderBy("category_id", "desc")
    //         ->get();

    //     self::assertCount(2, $collection);
    //     self::assertEquals("SMARTPHONE", $collection[0]->category_id);
    //     self::assertEquals("FOOD", $collection[1]->category_id);
    //     self::assertEquals(2, $collection[0]->total_product);
    //     self::assertEquals(2, $collection[1]->total_product);
    // }

    // public function testGroupByHaving()
    // {
    //     $this->insertProducts();
    //     $this->insertProductFood();

    //     $collection = DB::table("products")
    //         ->select("category_id", DB::raw("count(*) as total_product"))
    //         ->groupBy("category_id")
    //         ->having(DB::raw("count(*)"), ">", 2)
    //         ->orderBy("category_id", "desc")
    //         ->get();

    //     self::assertCount(0, $collection);
    // }

    // public function testLocking()
    // {
    //     $this->insertProducts();

    //     DB::transaction(function () {
    //         $collection = DB::table("products")
    //             ->where('id', '=', '1')
    //             ->lockForUpdate()
    //             ->get();

    //         self::assertCount(1, $collection);
    //     });
    // }

    // public function testPagination()
    // {
    //     $this->insertCategories();

    //     $paginate = DB::table("categories")->paginate(perPage: 2, page: 2);

    //     self::assertEquals(2, $paginate->currentPage());
    //     self::assertEquals(2, $paginate->perPage());
    //     self::assertEquals(2, $paginate->lastPage());
    //     self::assertEquals(4, $paginate->total());

    //     $collection = $paginate->items();
    //     self::assertCount(2, $collection);
    //     foreach ($collection as $item) {
    //         Log::info(json_encode($item));
    //     }
    // }

    // public function testIterateAllPagination()
    // {
    //     $this->insertCategories();

    //     $page = 1;

    //     while (true) {
    //         $paginate = DB::table("categories")->paginate(perPage: 2, page: $page);

    //         if ($paginate->isEmpty()) {
    //             break;
    //         } else {
    //             $page++;

    //             $collection = $paginate->items();
    //             self::assertCount(2, $collection);
    //             foreach ($collection as $item) {
    //                 Log::info(json_encode($item));
    //             }
    //         }
    //     }
    // }

    // public function testCursorPagination()
    // {
    //     $this->insertCategories();

    //     $cursor = "id";
    //     while (true) {
    //         $paginate = DB::table("categories")->orderBy("id")->cursorPaginate(perPage: 2, cursor: $cursor);

    //         foreach ($paginate->items() as $item) {
    //             self::assertNotNull($item);
    //             Log::info(json_encode($item));
    //         }

    //         $cursor = $paginate->nextCursor();
    //         if ($cursor == null) {
    //             break;
    //         }
    //     }
    // }
}
