<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class RawQueryTest extends TestCase
{
    // setup
    protected function setUp(): void
    {
        // agar diawal datanya selalu dihapus
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::delete('delete from categories');
    }

    // crud
    public function testCrud()
    {
        // insert data 
        DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ? , ?)', [
            "GADGET",
            "Gadget",
            "Gadget Category",
            "2020-10-10 10:10:10"
        ]);

        // melakukan select data 
        $results = DB::select('select * from categories where id = ?',  ['GADGET']);

        // hasilnya harus
        self::assertCount(1, $results);
        self::assertEquals('GADGET', $results[0]->id);
        self::assertEquals('Gadget', $results[0]->name);
        self::assertEquals('Gadget Category', $results[0]->description);
        self::assertEquals("2020-10-10 10:10:10", $results[0]->created_at);
    }

    public function testCrudNamedParameter()
    {
        // named parameter
        DB::insert('insert into categories(id, name, description, created_at) values (:id, :name, :description , :created_at)', [
            // asosiatif array
            "id" => "GADGET",
            "name" => "Gadget",
            "description" => "Gadget Category",
            "created_at" => "2020-10-10 10:10:10",
        ]);

        // select data berdasarkan id GADGET
        $results = DB::select('select * from categories where id = ?',  ['GADGET']);

        // hasil yang harus ada
        self::assertCount(1, $results);
        self::assertEquals('GADGET', $results[0]->id);
        self::assertEquals('Gadget', $results[0]->name);
        self::assertEquals('Gadget Category', $results[0]->description);
        self::assertEquals("2020-10-10 10:10:10", $results[0]->created_at);
    }
}
