<?php

namespace Tests\Feature;

use Illuminate\Database\QueryException;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;
use function PHPUnit\Framework\assertCount;

class TransactionTest extends TestCase
{
    // agar diawalnya selalu dihapus
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::delete('delete from categories');
    }

    // transaction success
    public function testTransactionSuccess()
    {
        // transaction(function), function tersebut kita bisa melakukan perintah database, jika terjadi error, secara otomatis transaksi akan di rollback
        // ada 2 data 
        DB::transaction(function () {
            DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ? , ?)', [
                "GADGET",
                "Gadget",
                "Gadget Category",
                "2020-10-10 10:10:10"
            ]);
            DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ? , ?)', [
                "FOOD",
                "Food",
                "Food Category",
                "2020-10-10 10:10:10"
            ]);
        });

        // tampilka data category
        $results = DB::select("select * from categories");
        self::assertCount(2, $results);
    }

    // gagal
    public function testTransactionFailed()
    {
        try {
            DB::transaction(function () {
                DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ? , ?)', [
                    "GADGET",
                    "Gadget",
                    "Gadget Category",
                    "2020-10-10 10:10:10"
                ]);
                DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ? , ?)', [
                    "GADGET",
                    "Food",
                    "Food Category",
                    "2020-10-10 10:10:10"
                ]);
            });
        } catch (QueryException $error) {
            // expected
        }

        // tampilka data category, harusnya tetap kosong karena gagal
        $results = DB::select("select * from categories");
        self::assertCount(0, $results);
    }

    // munual transaksi success
    public function testMaualTransactionSuccess()
    {
        try {
            // beginTransaction(), untuk memulai transaksi
            DB::beginTransaction();
            DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ? , ?)', [
                "GADGET",
                "Gadget",
                "Gadget Category",
                "2020-10-10 10:10:10"
            ]);
            DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ? , ?)', [
                "FOOD",
                "Food",
                "Food Category",
                "2020-10-10 10:10:10"
            ]);
            DB::commit(); // untuk melakukan commit transaksi
        } catch (QueryException $error) {
            DB::rollBack(); // untuk melakukan rollback transaksi
        }

        // tampilka data category
        $results = DB::select("select * from categories");
        self::assertCount(2, $results);
    }

    // test manual transaksi gagal
    public function testMaualTransactionFailed()
    {
        try {
            // beginTransaction(), untuk memulai transaksi
            DB::beginTransaction();
            DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ? , ?)', [
                "GADGET",
                "Gadget",
                "Gadget Category",
                "2020-10-10 10:10:10"
            ]);
            DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ? , ?)', [
                "GADGET",
                "Food",
                "Food Category",
                "2020-10-10 10:10:10"
            ]);
            DB::commit();
        } catch (QueryException $error) {
            DB::rollBack();
        }

        // tampilka data category
        $results = DB::select("select * from categories");
        self::assertCount(0, $results);
    }
}
